name: Build and Deploy

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: 16.19.0
      - name: restore node_modules
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.19.0
      - name: Install dependencies and build
        run: |
          npm ci
      - name: save node_modules
        uses: actions/cache/save@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

  deploy:
    if: github.ref == 'refs/heads/dev'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: 16.19.0
          clean: true
      - name: restore node_modules
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Force push "dev" branch to "main"
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "Bip Bup"
          npm run pre-deploy
          git add .
          git commit -m 'timestamp'
          git push origin HEAD:main --force
